services:
  api:
    build: .
    image: proauto-api:local
    container_name: proauto-api
    ports:
      - "5007:5007"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TZ=America/Sao_Paulo
    volumes:
      - /var/proauto/curriculos:/app/curriculos
      - /var/proauto/upload/images:/app/upload/images
      - /var/proauto/upload/equipment:/app/upload/equipment
      - /var/proauto/upload/profile:/app/upload/profile
      - /var/proauto/upload/signature:/app/upload/signature
      - /var/proauto/funcionario/holerite:/app/funcionario/holerite
      - /var/proauto/funcionario/documentos:/app/funcionario/documentos
      - /var/proauto/funcionario/reembolsos:/app/funcionario/reembolsos
      - /var/proauto/funcionario/atestados:/app/funcionario/atestados
      - /var/proauto/recibos-locacao:/app/recibos-locacao
      - /var/proauto/upload/gallery:/app/galeria
    restart: always
    networks:
      - db-network

networks:
  db-network:
    external: true
    name: api_postgres-compose-network