spring.datasource.url=jdbc:postgresql://localhost:5432/flexpro
spring.datasource.username=postgres
spring.datasource.password=Development@123
server.port=${SERVER_PORT}

api.security.token.secret= {JWT__SECRET:my-secret-key}

spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.from=${SMTP_FROM}
spring.mail.default-encoding=UTF-8
spring.mail.test-connection=false

logging.level.root=INFO
logging.file.name=logs.log
logging.file.path=logs

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=2GB

server.tomcat.max-part-count=600

server.tomcat.max-part-header-size=2048
server.tomcat.max-http-form-post-size=2147483647
server.tomcat.max-swallow-size=2147483647