DECLARE @DATA_INICIO DATE='2026-06-01'; DECLARE @DATA_FIM DATE='2026-06-30'; DECLARE @CODPARC INT=NULL; 
SELECT CB.COD AS codigo_cliente,
       RTRIM(PAR.NOMEPARC) AS nome_do_cliente,
       PAR.EMAIL AS email_cliente,
       PAR.CODPARCMATRIZ AS codigo_matriz,
       RTRIM(PM.NOMEPARC) AS nome_matriz
  FROM (SELECT CAB.CODPARC AS COD
          FROM TGFCAB CAB JOIN TGFITE ITE ON CAB.NUNOTA=ITE.NUNOTA
         WHERE CAB.STATUSNOTA='L' AND CAB.TIPMOV IN ('V','D') AND CAB.CODTIPOPER IN (149,213,214,150,215,2201,220,3048,3200,36,130,169,218,173,266,270,269,342) 
           AND CAB.DTNEG BETWEEN @DATA_INICIO AND @DATA_FIM
           AND (@CODPARC IS NULL OR CAB.CODPARC=@CODPARC)
         GROUP BY CAB.CODPARC
        UNION
        SELECT CODPARC FROM TCSOSE
         WHERE DTFECHAMENTO BETWEEN @DATA_INICIO AND @DATA_FIM
           AND (@CODPARC IS NULL OR CODPARC=@CODPARC)
         GROUP BY CODPARC) CB
  LEFT JOIN TGFPAR PAR ON PAR.CODPARC = CB.COD
  LEFT JOIN TGFPAR PM ON PM.CODPARC = PAR.CODPARCMATRIZ
 ORDER BY CB.COD DESC
