DECLARE @DATA_INICIO DATE='2026-06-01'; DECLARE @DATA_FIM DATE='2026-06-30'; DECLARE @CODPARC INT=NULL; 
SELECT CAB.CODPARC AS codigo_cliente,
       COUNT(DISTINCT CAB.NUMNOTA) AS quantidade_notas_emitidas,
       COUNT(DISTINCT ITE.CODPROD) AS quantidade_de_produtos,
       CONVERT(DECIMAL(18,2), SUM(ITE.QTDNEG)) AS quantidade_de_litros,
       CONVERT(DECIMAL(18,2), SUM((ITE.VLRTOT+ITE.VLRIPI+ITE.VLRSUBST-ITE.VLRDESC)*CASE WHEN CAB.TIPMOV='D' THEN -1 ELSE 1 END)) AS faturamento_total
  FROM TGFCAB CAB JOIN TGFITE ITE ON CAB.NUNOTA=ITE.NUNOTA
 WHERE CAB.STATUSNOTA='L' AND CAB.TIPMOV IN ('V','D') AND CAB.CODTIPOPER IN (149,213,214,150,215,2201,220,3048,3200,36,130,169,218,173,266,270,269,342) 
   AND CAB.DTNEG BETWEEN @DATA_INICIO AND @DATA_FIM
   AND (@CODPARC IS NULL OR CAB.CODPARC=@CODPARC)
 GROUP BY CAB.CODPARC
