DECLARE @DATA_INICIO DATE='2026-06-01'; DECLARE @DATA_FIM DATE='2026-06-30'; DECLARE @CODPARC INT=NULL; 
SELECT CODPARC AS codigo_cliente,
       COUNT(NUMOS) AS quantidade_de_visitas,
       CONVERT(DECIMAL(18,2), AVG(DATEDIFF(DAY, DHCHAMADA, DTFECHAMENTO))) AS media_dias_atendimento
  FROM TCSOSE
 WHERE DTFECHAMENTO BETWEEN @DATA_INICIO AND @DATA_FIM
   AND (@CODPARC IS NULL OR CODPARC=@CODPARC)
 GROUP BY CODPARC
