DECLARE @DATA_INICIO DATE='2026-06-01'; DECLARE @DATA_FIM DATE='2026-06-30'; DECLARE @CODPARC INT=NULL; 
SELECT MAN.CODPARC AS codigo_cliente,
       CONVERT(DECIMAL(18,2), SUM(ISNULL(PCS.QTD,0)*ISNULL(CUS.CUSGER,0))) AS valor_de_pecas_trocadas
  FROM AD_MANUTPCS PCS
  JOIN AD_MANUTENCAO MAN ON MAN.NUMOS = PCS.NUMOS
  LEFT JOIN TGFCUS CUS ON CUS.CODPROD = PCS.PECA
 WHERE MAN.DTFECHAMENTO BETWEEN @DATA_INICIO AND @DATA_FIM
   AND (@CODPARC IS NULL OR MAN.CODPARC=@CODPARC)
 GROUP BY MAN.CODPARC
