DECLARE @DATA_INICIO DATE='2026-06-01'; DECLARE @DATA_FIM DATE='2026-06-30'; DECLARE @CODPARC INT=NULL; 
SELECT X.CODPARC AS codigo_cliente, RTRIM(X.DESCRPROD) AS produto_em_destaque
  FROM (SELECT CAB.CODPARC, PRO.DESCRPROD,
               ROW_NUMBER() OVER (PARTITION BY CAB.CODPARC ORDER BY COUNT(*) DESC) AS RN
          FROM TGFCAB CAB
          JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
          JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
         WHERE CAB.STATUSNOTA='L' AND CAB.TIPMOV IN ('V','D')
           AND CAB.DTNEG BETWEEN @DATA_INICIO AND @DATA_FIM
           AND (@CODPARC IS NULL OR CAB.CODPARC=@CODPARC)
         GROUP BY CAB.CODPARC, PRO.DESCRPROD) X
 WHERE X.RN = 1
