UPDATE user_roles
SET role = CASE role
    WHEN '0' THEN 'ADMIN'
    WHEN '1' THEN 'USER'
    WHEN '2' THEN 'RH'
    WHEN '3' THEN 'DEVELOPER'
    WHEN '4' THEN 'VENDEDOR'
    WHEN '5' THEN 'ADMINISTRATIVO'
    WHEN '6' THEN 'FINANCEIRO'
    WHEN '7' THEN 'DESIGN'
    WHEN '8' THEN 'MARKETING'
    WHEN '9' THEN 'CONTATOS'
    WHEN '10' THEN 'CLIENTE'
    WHEN '11' THEN 'PARCEIRO'
    WHEN '12' THEN 'TECNICO'
    WHEN '13' THEN 'COMPRADOR'
    WHEN '14' THEN 'MANUTENCAO'
    WHEN '15' THEN 'PRODUCAO'
    WHEN '16' THEN 'ALMOXARIFADO'
    ELSE role
END
WHERE role ~ '^[0-9]+$'